
VisualMonk:
  snapshotPath: ./
  snapshotName: ${name}_${browser}_${width}
  baseUrl: http://localhost:8000
  windowSizes:
    desktop:
      width: 1440
      height:
    tablet:
      width:  901
      height:
    mobile:
      width:  600
      height:

SiteCrawler:
  host: localhost
  port: 8000
  siteIndexFile: ./siteIndex.json
  parseHTMLComments: false
  parseScriptTags: false
  stripQuerystring: true
  maxConcurrency: 30
  IGNORE_URLS_REGEX: /\/ask-cfpb\//
  errorThreshold: 100

Cucumber:
  specsBasePath: ../cucumber/features/*.feature
  suites:
    default: ../cucumber/features/*.feature

  testName: 'visual-monk'
