
VisualMonk:
  snapShotPath: ./
  baseUrl: http://localhost:8000
  windowSizes:
    default:
      width: 1440
      height: 900
    desktop:
      width:  1200
      height: 900
    tablet:
      width:  768,
      height: 1024
    mobile:
      width:  600,
      height: 740

SiteCrawler:
  host: localhost
  port: 8000
  siteIndexFile: ./siteIndex.json
  parseHTMLComments: false
  parseScriptTags: false
  stripQuerystring: true
  maxConcurrency: 30
  IGNORE_URLS_REGEX: /\/ask-cfpb\//
  errorThreshold: 100

Cucumber:
  specsBasePath: ../cucumber/features/*.feature
  suites:
    default: ../cucumber/features/*.feature

  testName: 'visual-monk'